# fly.toml app configuration file generated for drkstrife-site on 2023-11-02T10:08:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "drkstrife-site"
primary_region = "ord"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[env]
  RAILS_STORAGE = "/mnt/volume/storage"

[mounts]
  source = "storage_volume"
  destination = "/mnt/volume"
